const CLEAR_INDICATORS = "CLEAR_INDICATORS";
const ADD_INDICATOR = "ADD_INDICATOR";
const TOGGLE_INDICATORS = "TOGGLE_INDICATORS";
const GET_NETWORK_CALLS = "GET_NETWORK_CALLS";
const SHOW_API_MODAL = "SHOW_API_MODAL";
const ELEMENT_SELECTED = "ELEMENT_SELECTED";
const NEW_NETWORK_CALL = "NEW_NETWORK_CALL";
const GET_MAPPINGS = "GET_MAPPINGS";
const ADD_MAPPING = "ADD_MAPPING";
const REMOVE_MAPPING = "REMOVE_MAPPING";
const CLEAR_MAPPINGS = "CLEAR_MAPPINGS";
const GET_SELECTED_MAPPING = "GET_SELECTED_MAPPING";
const SET_SELECTED_MAPPING = "SET_SELECTED_MAPPING";
const CLEAR_SELECTED_MAPPING = "CLEAR_SELECTED_MAPPING";

// ERROR: Unexpected token:
export const BLOCKED_BY_CLIENT = "net::ERR_BLOCKED_BY_CLIENT";

export {
  CLEAR_INDICATORS,
  ADD_INDICATOR,
  TOGGLE_INDICATORS,
  GET_NETWORK_CALLS,
  SHOW_API_MODAL,
  ELEMENT_SELECTED,
  NEW_NETWORK_CALL,
  GET_MAPPINGS,
  ADD_MAPPING,
  REMOVE_MAPPING,
  CLEAR_MAPPINGS,
  GET_SELECTED_MAPPING,
  SET_SELECTED_MAPPING,
  CLEAR_SELECTED_MAPPING,
};
